server:
  port: 8001
spring:
  application:
    name: service-edu
  profiles:
    active: dev
  datasource:
    hikari:
      max-lifetime: 120000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Edu?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 180000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/gee/edu/mapper/xml/*.xml
#开启熔断机制
feign:
  hystrix:
    enabled: true
sensitiveWords:
  - 法轮功比较好
  - Fuck