server:
  port: 8003
spring:
  application:
    name: service-vod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB     #最大上传单个文件大小：默认1M
      max-request-size: 1024MB  #最大置总上传的数据大小 ：默认10M
aliyun:
  vod:
    file:
      keyid: LTAI4G5Zf81jhYfrfZpzpfx2
      keysecret: ukjsTIBpxy2WYlNxVtAhRct2SmJcNV