server:
  port: 8005
spring:
  application:
    name: service-msg
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 180000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
accesskey: LTAI4G5Zf81jhYfrfZpzpfx2
screct: ukjsTIBpxy2WYlNxVtAhRct2SmJcNV